events {}
http {
  server {
    listen 80;
    server_tokens off;

    location ^~ /regtest/ {
      proxy_pass http://esplora:80;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }

    location ^~ /regtest/api/ {
      rewrite ^/regtest/api/(.*)$ /$1 break;
      proxy_pass http://electrs:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      add_header Cache-Control "no-store";
    }

    location ~ ^/regtest/(blocks|block|txs|tx|mempool|fee-estimates)(/.*)?$ {
      rewrite ^/regtest/(.*)$ /$1 break;
      proxy_pass http://electrs:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      add_header Cache-Control "no-store";
    }

    location ^~ /testnet/ {
      proxy_pass http://esplora:80;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }

    location ^~ /testnet/api/ {
      rewrite ^/testnet/api/(.*)$ /$1 break;
      proxy_pass http://electrs:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      add_header Cache-Control "no-store";
    }

    location ~ ^/testnet/(blocks|block|txs|tx|mempool|fee-estimates)(/.*)?$ {
      rewrite ^/testnet/(.*)$ /$1 break;
      proxy_pass http://electrs:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      add_header Cache-Control "no-store";
    }

    location ^~ /api/ {
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://electrs:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      add_header Cache-Control "no-store";
    }

    location ^~ / {
      proxy_pass http://esplora:80;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }

  }
}